function varargout = help(varargin)
% HELP MATLAB code for help.fig
%      HELP, by itself, creates a new HELP or raises the existing
%      singleton*.
%
%      H = HELP returns the handle to a new HELP or the handle to
%      the existing singleton*.
%
%      HELP('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in HELP.M with the given input arguments.
%
%      HELP('Property','Value',...) creates a new HELP or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before help_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to help_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES

% Edit the above text to modify the response to help help

% Last Modified by GUIDE v2.5 05-Sep-2012 18:17:45

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @help_OpeningFcn, ...
                   'gui_OutputFcn',  @help_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT


% --- Executes just before help is made visible.
function help_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to help (see VARARGIN)
pos=get(handles.figure1,'Position');
newpos=round(get(0,'ScreenSize')/2-pos/2);
set(handles.figure1,'Position',[newpos(3) newpos(4) pos(3) pos(4)]);

text=sprintf([ ...
'\n'...
'———————————Tips to get a better analysis———————————'...
'\n\n'...
'•Gray card has to fully appear in every image, focused.'...
'\n\n'...
'•If results are consistantly not satisfactory, try changing parameters in '...
'the options screen. This screen is accessible via the gear button in the '...
'main screen.'...
'\n\n'...
'•For a tighter spot marking, reduce the ''estimalted spot size'' in the options screen.'...
'\n\n'...
'•When you mark an area in the main screen:'...
'\n\n'...
'    •Don''t mark areas that are not a part of the barn owl.'...
'\n\n'...
'    •Try not to include dark objects, such as feathers, dark stains etc.'...
'\n\n'...
'    •Try not to mark spots that are very different from each other, like light \n'...
'     spots with dark ones; spots that have soft edges with ones that have \n'...
'     strong edges; etc.'...
'\n\n'...
'————————————————  FAQ  ———————————————'...
'\n\n'...
'•Where is my data?\n'...
'Processed data is saved into Excel files. Their location is specified in the '...
'options screen. Each Excel file refers to all the results extracted from '...
'a single program session. File names indicate the time in '...
'which the first result was saved.'...
'\n\n'...
'•What is eccentricity?\n'...
'Eccentricity is a value between 0 and 1 that indicates similarity to '...
'a perfect circle: the more eccentricity is closer to 1, the '...
'more a shape is similar to a streched circle (and not a perfect one).'...
'\n\n'...
'•How can I stop a drawing mode in the middle?\n'...
'Unfortunately, you can''t. It is very unrecommended to disrupt drawing, '...
'because the program''s behaviour is not expected in such a case.'...
'\n\n'...
'•Where is the fixed size rectangle marker?\n'...
'It''s in the center of the picture, when fully zoom out.'...
'\n\n'...
'•How can I edit processed data?\n'...
'Processed data can only be edited using Microsoft Excel.'...
'\n\n'...
'•What is night mode?\n'...
'Night mode is an "automatic pilot" for image calibration. Calibration takes '...
'a lot of time, so do it when you don''t need the computer - instead of '...
'waiting when you load an image to the program.'...
'\n\n'...
'•Why does night mode respond so slowly?\n'...
'While calibrating, night mode responds only when a current calibration '...
'is completed.'...
'\n\n'...
'—————————————  Troubleshooting —————————————'...
'\n\n'...
'•Data is lost or overwritten.\n'...
'Data might be overwritten only if two barn owls were analysed at '...
'the same minute.'...
'\n\n'...
'•Fixed-rectangle marking method generates errors.\n'...
'It''s probably because the fixed width or hight, specified in the options '...
'screen, are bigger than the image.'...
'\n\n'...
'•Changing parameters doesn''t have any influence.\n'...
'The safest way to ensure application of new parameters from the options '...
'screen is to reload the image.'...
'\n\n'...
'———————————————— About ———————————————'...
'\n\n'...
'This program was created by Naftali Kizner, an electrical engineering '...
'student in the Technion - the Israeli institute of technology. The program '...
'is the final result of a semestral project offered by SIPL - the Signal '...
'and Image Processing Lab. The project was ordered by the Department of '...
'Zeology of Tel Aviv University, and was supervised by Yuval Bahat. It was '...
'developed since January 2012 until Septemper 2012.'...
'\n\n'...
'Further questions will be kindly answered.\n'...
'Email adress: snaftali@t2.technion.ac.il'...
'\n\n'...
'© 2012 Naftali Kizner all rights reserved'...
]);

set(handles.edit1,'String',text);


% Choose default command line output for help
handles.output = hObject;

% Update handles structure
guidata(hObject, handles);

% UIWAIT makes help wait for user response (see UIRESUME)
% uiwait(handles.figure1);


% --- Outputs from this function are returned to the command line.
function varargout = help_OutputFcn(hObject, eventdata, handles) 
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Get default command line output from handles structure
varargout{1} = handles.output;

function edit1_CreateFcn(hObject, eventdata, handles)
